# DET Advanced — high-value vocabulary for DET 130+ target
# Format: (word, Korean meaning, example, synonyms)

ADVANCED = [
    # ── 학술 동사 ──────────────────────────────────────────────
    ("advocate", "옹호하다, 주장하다", "She advocates for stricter environmental laws.", "support, champion, promote"),
    ("alleviate", "완화하다, 경감하다", "Rest can alleviate stress.", "ease, relieve, reduce"),
    ("articulate", "명확히 표현하다; 분명한", "He articulated his ideas clearly.", "express, convey, voice"),
    ("ascertain", "확인하다, 알아내다", "We need to ascertain the facts.", "determine, find out, verify"),
    ("augment", "늘리다, 증가시키다", "She augmented her income with freelance work.", "increase, enhance, supplement"),
    ("bolster", "강화하다, 북돋우다", "New evidence bolsters the theory.", "strengthen, reinforce, support"),
    ("circumvent", "우회하다, 피하다", "They tried to circumvent the rules.", "bypass, avoid, get around"),
    ("collaborate", "협력하다, 공동 작업하다", "Scientists collaborate to solve global problems.", "cooperate, work together, partner"),
    ("delineate", "묘사하다, 윤곽을 그리다", "The report delineates the main challenges.", "describe, outline, define"),
    ("depict", "묘사하다, 나타내다", "The painting depicts a rural scene.", "portray, show, represent"),
    ("discern", "식별하다, 분간하다", "It is hard to discern the truth.", "perceive, detect, distinguish"),
    ("disseminate", "전파하다, 보급하다", "The internet disseminates information rapidly.", "spread, distribute, circulate"),
    ("elaborate", "자세히 설명하다; 정교한", "Could you elaborate on your point?", "explain in detail, expand, develop"),
    ("encompass", "포함하다, 아우르다", "The course encompasses many topics.", "include, cover, embrace"),
    ("foster", "육성하다, 촉진하다", "Schools foster creativity in students.", "encourage, nurture, promote"),
    ("hinder", "방해하다, 저해하다", "Lack of sleep hinders performance.", "impede, obstruct, hamper"),
    ("impede", "방해하다, 지연시키다", "Bureaucracy can impede progress.", "hinder, block, obstruct"),
    ("infer", "추론하다, 추측하다", "What can we infer from the data?", "deduce, conclude, gather"),
    ("mitigate", "완화하다, 줄이다", "We must mitigate the risks.", "reduce, lessen, alleviate"),
    ("portray", "묘사하다, 표현하다", "The novel portrays life in the 19th century.", "depict, represent, describe"),
    ("scrutinize", "꼼꼼히 조사하다", "Auditors scrutinize financial records.", "examine closely, inspect, analyze"),
    ("speculate", "추측하다, 사색하다", "Experts speculate about the cause.", "guess, theorize, hypothesize"),
    ("undermine", "약화시키다, 손상시키다", "Constant criticism undermines confidence.", "weaken, erode, subvert"),
    ("validate", "검증하다, 확인하다", "Validate your findings with further tests.", "confirm, verify, substantiate"),
    ("contend", "주장하다; 경쟁하다", "She contends that the policy is flawed.", "argue, claim, assert"),
    ("contrive", "고안하다, 꾸미다", "They contrived a solution to the problem.", "devise, engineer, invent"),
    ("corroborate", "확증하다, 뒷받침하다", "Witnesses corroborated his account.", "confirm, support, verify"),
    ("culminate", "절정에 달하다", "Years of work culminated in success.", "peak, climax, result in"),
    ("diminish", "줄어들다, 약화시키다", "Noise diminishes concentration.", "reduce, lessen, decrease"),
    ("elicit", "이끌어 내다, 유발하다", "The question elicited a strong reaction.", "evoke, draw out, provoke"),
    ("exacerbate", "악화시키다", "Stress can exacerbate health problems.", "worsen, aggravate, intensify"),
    ("exemplify", "예시하다, 전형이 되다", "This case exemplifies the problem well.", "illustrate, demonstrate, typify"),
    ("gauge", "측정하다; 가늠하다", "It is difficult to gauge public opinion.", "measure, assess, estimate"),
    ("illuminate", "밝히다, 명확히 하다", "The study illuminates an overlooked issue.", "clarify, shed light on, explain"),
    ("inhibit", "억제하다, 방해하다", "Fear inhibits creative thinking.", "hinder, prevent, suppress"),
    ("mandate", "의무화하다; 명령", "The law mandates annual inspections.", "require, order, compel"),
    ("merit", "가치가 있다; 장점", "The idea merits further consideration.", "deserve, warrant, be worth"),
    ("negate", "부정하다, 무효화하다", "One error can negate all progress.", "nullify, cancel, invalidate"),
    ("obscure", "모호하게 하다; 잘 알려지지 않은", "Technical jargon can obscure meaning.", "hide, conceal, complicate"),
    ("pertain", "관련되다, 해당되다", "These rules pertain to all staff.", "relate, apply, concern"),
    ("postulate", "가정하다, 공리로 세우다", "She postulated a new theory.", "assume, hypothesize, propose"),
    ("presuppose", "전제하다, 예상하다", "The plan presupposes sufficient funding.", "assume, take for granted, imply"),
    ("proliferate", "급증하다, 번성하다", "Social media platforms have proliferated.", "multiply, spread, increase rapidly"),
    ("reconcile", "화해시키다; 조화시키다", "It is hard to reconcile the two views.", "harmonize, resolve, make consistent"),
    ("rectify", "바로잡다, 수정하다", "Steps were taken to rectify the error.", "correct, fix, remedy"),
    ("refute", "반박하다, 논박하다", "She refuted the claim with evidence.", "disprove, rebut, counter"),
    ("reiterate", "반복하다, 되풀이하다", "Let me reiterate the main points.", "repeat, restate, emphasize again"),
    ("substantiate", "입증하다, 실증하다", "Can you substantiate your claims?", "prove, confirm, verify"),
    ("supersede", "대체하다, 능가하다", "New technology supersedes old methods.", "replace, displace, succeed"),
    ("transcend", "초월하다, 능가하다", "Great art transcends cultural boundaries.", "go beyond, surpass, exceed"),

    # ── 고급 형용사 ────────────────────────────────────────────
    ("ambivalent", "양면적인, 상반된 감정의", "She felt ambivalent about the decision.", "conflicted, undecided, torn"),
    ("analogous", "유사한, 비슷한", "The situation is analogous to last year.", "similar, comparable, parallel"),
    ("arbitrary", "임의적인, 독단적인", "The rule seems arbitrary and unfair.", "random, capricious, unreasoned"),
    ("coherent", "일관된, 논리적인", "Present a coherent argument.", "logical, consistent, clear"),
    ("contentious", "논쟁의 여지가 있는", "Climate policy is a contentious issue.", "controversial, disputed, debatable"),
    ("elusive", "파악하기 어려운, 잡기 힘든", "The solution remained elusive.", "hard to find, fleeting, intangible"),
    ("erroneous", "잘못된, 부정확한", "The report contained erroneous data.", "incorrect, wrong, mistaken"),
    ("excessive", "과도한, 지나친", "Excessive stress is harmful.", "extreme, too much, unreasonable"),
    ("feasible", "실현 가능한, 타당한", "Is the plan feasible within budget?", "possible, practicable, viable"),
    ("formidable", "강력한, 만만치 않은", "She faced formidable challenges.", "daunting, powerful, impressive"),
    ("imperative", "필수적인; 명령법", "It is imperative to act now.", "essential, crucial, necessary"),
    ("inherent", "내재된, 본래의", "There are inherent risks in the plan.", "inborn, natural, built-in"),
    ("intrinsic", "본질적인, 고유한", "The intrinsic value of education.", "essential, innate, fundamental"),
    ("lucid", "명쾌한, 명료한", "His explanation was lucid and helpful.", "clear, transparent, intelligible"),
    ("meticulous", "꼼꼼한, 세심한", "She is meticulous in her research.", "careful, thorough, precise"),
    ("paramount", "가장 중요한, 최우선의", "Safety is of paramount importance.", "most important, supreme, chief"),
    ("pervasive", "만연한, 널리 퍼진", "Social media has a pervasive influence.", "widespread, ubiquitous, prevalent"),
    ("plausible", "그럴듯한, 믿을 만한", "His explanation sounds plausible.", "credible, believable, reasonable"),
    ("profound", "심오한, 깊은", "The discovery had a profound impact.", "deep, significant, far-reaching"),
    ("redundant", "불필요한, 중복된", "The sentence contains redundant words.", "superfluous, unnecessary, repetitive"),
    ("robust", "강건한, 튼튼한", "We need a robust methodology.", "strong, sturdy, resilient"),
    ("salient", "두드러진, 가장 중요한", "Highlight the salient points.", "prominent, notable, key"),
    ("substantial", "상당한, 실질적인", "There was a substantial improvement.", "considerable, significant, large"),
    ("subtle", "미묘한, 포착하기 어려운", "There is a subtle difference between them.", "delicate, fine, understated"),
    ("systematic", "체계적인, 조직적인", "A systematic approach is needed.", "methodical, organized, structured"),
    ("tangible", "유형의, 실재하는", "We need tangible evidence.", "concrete, real, physical"),
    ("tentative", "잠정적인, 확정되지 않은", "These are tentative conclusions.", "provisional, preliminary, uncertain"),
    ("trivial", "사소한, 하찮은", "Don't waste time on trivial matters.", "minor, insignificant, petty"),
    ("ubiquitous", "어디에나 있는, 도처에 있는", "Smartphones are now ubiquitous.", "everywhere, omnipresent, universal"),
    ("versatile", "다재다능한, 다용도의", "She is a versatile writer.", "flexible, adaptable, all-round"),
    ("viable", "실행 가능한, 생존 가능한", "Is this a viable solution?", "feasible, workable, practicable"),
    ("volatile", "변동이 심한; 불안정한", "The stock market is volatile.", "unstable, unpredictable, changeable"),

    # ── 고급 명사 ──────────────────────────────────────────────
    ("abstraction", "추상화, 추상적 개념", "Philosophy deals with abstraction.", "concept, generalization, idea"),
    ("adversity", "역경, 고난", "She thrived despite adversity.", "hardship, difficulty, misfortune"),
    ("assertion", "주장, 단언", "His assertion lacks supporting evidence.", "claim, statement, declaration"),
    ("coherence", "일관성, 논리적 연결", "The essay lacks coherence.", "consistency, logic, unity"),
    ("connotation", "함축, 내포된 의미", "The word has negative connotations.", "implication, undertone, association"),
    ("deduction", "공제; 연역, 추론", "Logical deduction leads to the answer.", "reasoning, inference, conclusion"),
    ("deficiency", "결핍, 부족", "A vitamin deficiency can cause illness.", "lack, shortage, inadequacy"),
    ("discrepancy", "불일치, 차이", "There is a discrepancy in the figures.", "inconsistency, difference, gap"),
    ("distinction", "차이; 탁월함", "There is a clear distinction between them.", "difference, contrast, differentiation"),
    ("fallacy", "오류, 잘못된 생각", "That argument is based on a fallacy.", "error, misconception, false belief"),
    ("feasibility", "실현 가능성", "Study the feasibility of the project.", "practicality, viability, possibility"),
    ("inference", "추론, 결론", "Draw an inference from the data.", "conclusion, deduction, interpretation"),
    ("integrity", "성실함; 온전함", "Act with integrity in all situations.", "honesty, uprightness, wholeness"),
    ("misconception", "오해, 잘못된 생각", "There are many misconceptions about diet.", "misunderstanding, false belief, error"),
    ("nuance", "뉘앙스, 미묘한 차이", "Understand the nuances of the language.", "subtlety, shade, fine distinction"),
    ("perception", "인식, 지각", "Our perception of risk varies.", "awareness, view, understanding"),
    ("precedent", "선례, 전례", "This sets a dangerous precedent.", "example, model, prior case"),
    ("premise", "전제, 근거", "The argument rests on a faulty premise.", "assumption, basis, presupposition"),
    ("prevalence", "보급, 만연", "The prevalence of obesity is rising.", "frequency, commonness, widespread occurrence"),
    ("rhetoric", "수사법; 미사여구", "The speech was full of empty rhetoric.", "persuasive language, oratory, eloquence"),
    ("scrutiny", "면밀한 조사, 세밀한 검토", "The decision came under public scrutiny.", "close examination, inspection, attention"),
    ("speculation", "추측, 사색; 투기", "There is much speculation about the cause.", "conjecture, theory, guesswork"),
    ("testimony", "증언, 증거", "Her testimony was crucial to the case.", "evidence, statement, account"),
    ("validity", "타당성, 유효성", "Question the validity of the results.", "soundness, legitimacy, credibility"),
    ("ambiguity", "모호함, 애매함", "Avoid ambiguity in academic writing.", "vagueness, uncertainty, double meaning"),
    ("consensus", "합의, 의견 일치", "There is broad consensus on this issue.", "agreement, accord, unanimity"),
    ("dichotomy", "이분법, 이원 대립", "The dichotomy between theory and practice.", "division, contrast, split"),
    ("disposition", "성향, 기질; 배치", "She has a disposition toward caution.", "tendency, inclination, temperament"),
    ("endeavor", "노력, 시도", "Her endeavors finally paid off.", "effort, attempt, undertaking"),
    ("expenditure", "지출, 비용", "Government expenditure on health rose.", "spending, outlay, expense"),
    ("hierarchy", "위계, 계층 구조", "Challenge the existing hierarchy.", "ranking, order, pecking order"),
    ("hypothesis", "가설", "The hypothesis was tested experimentally.", "theory, assumption, postulate"),
    ("incentive", "동기, 유인책", "Offer an incentive to increase productivity.", "motivation, stimulus, reward"),
    ("magnitude", "규모, 크기", "The magnitude of the problem is clear.", "size, scale, extent"),
    ("paradigm", "패러다임, 사고의 틀", "A paradigm shift in science.", "model, framework, standard"),
    ("rationale", "이론적 근거, 이유", "Explain the rationale behind the decision.", "reason, justification, logic"),
    ("repercussion", "반향, 파장", "The decision had major repercussions.", "consequence, effect, impact"),
    ("resilience", "회복력, 탄력성", "Children show remarkable resilience.", "toughness, adaptability, strength"),
    ("skepticism", "회의주의, 의구심", "There is widespread skepticism about the plan.", "doubt, disbelief, questioning"),
    ("trajectory", "궤적, 진행 경로", "The economy is on an upward trajectory.", "path, course, direction"),

    # ── 접속·연결 표현 ─────────────────────────────────────────
    ("notwithstanding", "~에도 불구하고", "Notwithstanding the risks, they proceeded.", "despite, regardless of, in spite of"),
    ("consequently", "결과적으로, 따라서", "The experiment failed; consequently, it was repeated.", "therefore, as a result, hence"),
    ("conversely", "반대로, 역으로", "Conversely, some argue the opposite.", "on the other hand, in contrast, oppositely"),
    ("henceforth", "이후부터, 앞으로는", "Henceforth, all reports must be verified.", "from now on, in future, thereafter"),
    ("incidentally", "부수적으로, 그런데", "Incidentally, this also reduces costs.", "by the way, in passing, additionally"),
    ("inherently", "본질적으로", "The system is inherently flawed.", "fundamentally, essentially, naturally"),
    ("predominantly", "주로, 대부분", "The population is predominantly urban.", "mainly, mostly, largely"),
    ("presumably", "아마, 추정컨대", "Presumably, they will agree.", "probably, likely, apparently"),
    ("respectively", "각각, 순서대로", "A and B scored 90 and 85 respectively.", "separately, individually, in that order"),
    ("simultaneously", "동시에", "Events occurred simultaneously.", "at the same time, concurrently, together"),
    ("subsequently", "이후에, 뒤이어", "Subsequently, new evidence emerged.", "afterward, later, following this"),
    ("whereas", "반면에, ~인 데 비해", "He is outgoing, whereas she is reserved.", "while, in contrast, but"),
    ("whereby", "그것에 의해, ~하는 방법으로", "A system whereby votes are counted online.", "by which, through which, by means of"),
]
