# Academic Word List (AWL) — 570 headwords across 10 sublists
# Format: (word, Korean meaning, example, synonyms)

AWL = [
    # Sublist 1
    ("analyze", "분석하다", "Scientists analyze data to find patterns.", "examine, study, investigate"),
    ("approach", "접근 방법; 접근하다", "We need a new approach to solve this problem.", "method, strategy, technique"),
    ("area", "영역, 분야", "She works in the area of public health.", "region, field, domain"),
    ("assess", "평가하다", "Teachers assess students through tests.", "evaluate, appraise, measure"),
    ("assume", "가정하다, 추정하다", "Don't assume everyone agrees with you.", "presume, suppose, take for granted"),
    ("authority", "권위, 권한", "The government has authority over taxation.", "power, jurisdiction, control"),
    ("available", "이용 가능한", "Fresh water is not always available.", "accessible, obtainable, at hand"),
    ("benefit", "혜택, 이득", "Exercise has many health benefits.", "advantage, gain, profit"),
    ("concept", "개념", "The concept of justice varies across cultures.", "idea, notion, principle"),
    ("consist", "구성되다 (of)", "The team consists of ten members.", "comprise, be made up of, contain"),
    ("context", "맥락, 상황", "Understand words in context.", "background, setting, circumstances"),
    ("contract", "계약(서)", "She signed a two-year contract.", "agreement, deal, treaty"),
    ("create", "창조하다, 만들다", "Artists create works of beauty.", "make, produce, generate"),
    ("data", "데이터, 자료", "The data shows a rising trend.", "facts, figures, statistics"),
    ("define", "정의하다", "Define the term before using it.", "explain, describe, specify"),
    ("derive", "유래하다; 끌어내다", "Many English words derive from Latin.", "obtain, get, originate"),
    ("distribute", "분배하다, 배포하다", "The organization distributes food to refugees.", "spread, deliver, allocate"),
    ("economy", "경제", "The economy grew by three percent.", "financial system, trade, commerce"),
    ("environment", "환경", "We must protect the environment.", "surroundings, habitat, ecosystem"),
    ("establish", "설립하다, 확립하다", "They established a new company.", "found, set up, create"),
    ("estimate", "추정하다; 추정치", "Experts estimate the cost at millions.", "calculate, approximate, gauge"),
    ("evidence", "증거", "The evidence supports his claim.", "proof, data, indication"),
    ("export", "수출하다; 수출품", "Japan exports cars worldwide.", "sell abroad, ship out, trade"),
    ("factor", "요인, 요소", "Diet is a key factor in health.", "element, component, aspect"),
    ("finance", "재정, 금융", "She works in corporate finance.", "funding, investment, economics"),
    ("formula", "공식, 수식", "The formula for water is H₂O.", "equation, rule, expression"),
    ("function", "기능, 역할", "The function of a heart is to pump blood.", "purpose, role, task"),
    ("identify", "확인하다, 파악하다", "Can you identify the problem?", "recognize, pinpoint, determine"),
    ("income", "수입, 소득", "Her income doubled last year.", "earnings, revenue, salary"),
    ("indicate", "나타내다, 가리키다", "Results indicate a positive trend.", "show, signal, suggest"),
    ("individual", "개인; 개별적인", "Each individual has unique needs.", "person, single entity, unit"),
    ("interpret", "해석하다", "How do you interpret this poem?", "explain, construe, understand"),
    ("involve", "포함하다, 관련시키다", "The project involves many people.", "include, entail, require"),
    ("issue", "문제, 쟁점", "Climate change is a major issue.", "problem, matter, concern"),
    ("labor", "노동; 수고", "Manual labor is demanding.", "work, toil, effort"),
    ("legal", "법적인, 합법적인", "Get legal advice before signing.", "lawful, legitimate, judicial"),
    ("legislate", "법률을 제정하다", "Parliament legislates on taxation.", "enact laws, pass legislation"),
    ("major", "중요한, 주요한", "This is a major breakthrough.", "significant, important, key"),
    ("method", "방법, 방식", "What method do you use?", "procedure, technique, approach"),
    ("occur", "발생하다, 일어나다", "Earthquakes occur without warning.", "happen, take place, arise"),
    ("percent", "퍼센트, 백분율", "Fifty percent voted in favor.", "proportion, fraction, rate"),
    ("period", "기간, 시기", "A long period of silence followed.", "time, span, duration, phase"),
    ("policy", "정책, 방침", "The company has a strict safety policy.", "plan, strategy, guidelines"),
    ("principle", "원칙, 원리", "Follow the principle of fairness.", "rule, standard, guideline"),
    ("procedure", "절차, 과정", "Follow the correct procedure.", "process, method, protocol"),
    ("process", "과정; 처리하다", "Learning is a gradual process.", "procedure, series of steps, operation"),
    ("require", "요구하다, 필요로 하다", "This job requires experience.", "need, demand, call for"),
    ("research", "연구, 조사", "Research shows that sleep is vital.", "investigation, study, inquiry"),
    ("respond", "반응하다, 응답하다", "Please respond to my email.", "reply, answer, react"),
    ("role", "역할", "Education plays a key role.", "function, part, position"),
    ("section", "부분, 구역", "Read the first section carefully.", "part, portion, division"),
    ("significant", "중요한, 상당한", "There was a significant improvement.", "important, notable, meaningful"),
    ("similar", "비슷한, 유사한", "The two results are similar.", "alike, comparable, resembling"),
    ("source", "출처, 근원", "What is the source of this information?", "origin, root, basis"),
    ("specific", "구체적인, 특정한", "Be specific about what you need.", "particular, precise, exact"),
    ("structure", "구조, 체계", "The sentence structure is complex.", "organization, arrangement, framework"),
    ("theory", "이론", "Darwin's theory of evolution.", "hypothesis, explanation, model"),
    ("vary", "다르다, 변하다", "Prices vary from store to store.", "differ, change, fluctuate"),

    # Sublist 2
    ("achieve", "달성하다, 성취하다", "Hard work helps you achieve success.", "accomplish, attain, reach"),
    ("acquire", "습득하다, 얻다", "She acquired new skills online.", "gain, obtain, get"),
    ("administer", "관리하다, 운영하다", "Who administers this program?", "manage, run, oversee"),
    ("affect", "영향을 미치다", "Pollution affects our health.", "impact, influence, alter"),
    ("appropriate", "적절한", "Wear appropriate clothing.", "suitable, fitting, proper"),
    ("aspect", "측면, 양상", "Consider every aspect of the problem.", "feature, element, facet"),
    ("assist", "돕다, 지원하다", "Can you assist me with this?", "help, support, aid"),
    ("category", "범주, 종류", "Sort items into categories.", "class, group, type"),
    ("chapter", "장(章), 단원", "Read chapter three tonight.", "section, part, division"),
    ("commission", "위원회; 위임하다", "A commission was set up to investigate.", "committee, board, authority"),
    ("community", "공동체, 지역 사회", "The community supported the school.", "group, society, neighborhood"),
    ("complex", "복잡한; 복합 단지", "The issue is very complex.", "complicated, intricate, involved"),
    ("compute", "계산하다", "Computers compute data quickly.", "calculate, process, figure out"),
    ("conclude", "결론을 내리다; 끝내다", "We can conclude that X is true.", "decide, determine, deduce"),
    ("conduct", "수행하다; 행동", "They conducted an experiment.", "carry out, perform, execute"),
    ("consequent", "결과로 생기는", "The flood and consequent damage were severe.", "resulting, following, ensuing"),
    ("construct", "건설하다, 구성하다", "They constructed a new bridge.", "build, create, make"),
    ("consume", "소비하다", "Cars consume large amounts of fuel.", "use, devour, exhaust"),
    ("credit", "공로, 신용; 학점", "Give credit where it is due.", "recognition, acknowledgment, praise"),
    ("culture", "문화", "Every culture has unique traditions.", "society, civilization, heritage"),
    ("design", "설계하다; 디자인", "She designed the new logo.", "plan, create, devise"),
    ("distinct", "뚜렷이 다른, 명확한", "The two concepts are distinct.", "different, separate, unique"),
    ("element", "요소, 성분", "Trust is an element of teamwork.", "component, part, ingredient"),
    ("evaluate", "평가하다", "We need to evaluate the results.", "assess, appraise, judge"),
    ("feature", "특징, 특성", "A key feature of the plan.", "characteristic, aspect, quality"),
    ("final", "최종의, 마지막의", "This is the final stage.", "last, concluding, ultimate"),
    ("focus", "집중하다; 초점", "Focus on the main idea.", "concentrate, center, direct"),
    ("impact", "영향, 충격", "Technology has a huge impact.", "effect, influence, consequence"),
    ("injure", "부상을 입히다", "He was injured in an accident.", "harm, hurt, wound"),
    ("institute", "기관; 설립하다", "A research institute was founded.", "organization, establishment, foundation"),
    ("invest", "투자하다", "She invested in real estate.", "put money in, fund, finance"),
    ("item", "항목, 물품", "List each item separately.", "thing, object, unit"),
    ("maintain", "유지하다", "Maintain a healthy lifestyle.", "keep, preserve, sustain"),
    ("normal", "정상적인, 보통의", "Normal body temperature is 37°C.", "standard, regular, typical"),
    ("obtain", "얻다, 획득하다", "How did you obtain this?", "get, acquire, gain"),
    ("participate", "참가하다", "Participate in the discussion.", "take part, join, engage"),
    ("perceive", "인식하다, 감지하다", "How do you perceive this situation?", "see, sense, recognize"),
    ("positive", "긍정적인; 확실한", "She has a positive attitude.", "good, optimistic, affirmative"),
    ("potential", "가능성; 잠재적인", "She has great potential.", "capability, possibility, promise"),
    ("previous", "이전의", "My previous job was in banking.", "former, earlier, prior"),
    ("primary", "주요한, 1차적인", "Your primary goal is to pass.", "main, chief, principal"),
    ("purchase", "구매하다; 구매", "He purchased a new laptop.", "buy, acquire, obtain"),
    ("range", "범위; 다양한 종류", "A wide range of topics.", "variety, scope, spectrum"),
    ("region", "지역, 지방", "The northern region is cold.", "area, zone, territory"),
    ("regulate", "규제하다, 조절하다", "The government regulates food safety.", "control, govern, oversee"),
    ("relevant", "관련 있는, 적절한", "Provide relevant examples.", "related, applicable, pertinent"),
    ("reside", "거주하다", "She resides in Tokyo.", "live, dwell, inhabit"),
    ("resource", "자원, 재원", "Water is a vital resource.", "asset, supply, reserve"),
    ("restrict", "제한하다", "Access is restricted to staff.", "limit, confine, control"),
    ("secure", "안전한; 확보하다", "Make sure the door is secure.", "safe, stable, protected"),
    ("seek", "추구하다, 찾다", "She seeks a better opportunity.", "search for, look for, pursue"),
    ("select", "선택하다, 고르다", "Select the best option.", "choose, pick, opt for"),
    ("site", "장소, 부지", "The construction site is busy.", "location, place, spot"),
    ("strategy", "전략", "The team needs a better strategy.", "plan, approach, method"),
    ("survey", "조사하다; 설문 조사", "They surveyed public opinion.", "examine, study, investigate"),
    ("text", "글, 문서", "The text is difficult to understand.", "writing, words, content"),
    ("tradition", "전통, 관습", "Respect cultural traditions.", "custom, practice, convention"),
    ("transfer", "이동하다; 이전", "Transfer the files to the server.", "move, shift, transport"),

    # Sublist 3
    ("alternative", "대안; 대안적인", "Is there an alternative solution?", "option, choice, substitute"),
    ("circumstance", "상황, 환경", "The circumstances were unusual.", "condition, situation, context"),
    ("comment", "논평하다; 논평", "Please comment on the proposal.", "remark, note, observation"),
    ("compensate", "보상하다", "They compensated him for the damage.", "make up for, reimburse, offset"),
    ("component", "구성 요소, 부품", "A key component of the system.", "part, element, piece"),
    ("consent", "동의; 동의하다", "You need parental consent.", "permission, agreement, approval"),
    ("considerable", "상당한, 많은", "There was considerable resistance.", "significant, substantial, sizeable"),
    ("constant", "일정한, 지속적인", "The noise was constant.", "continuous, unchanging, steady"),
    ("constrain", "제약하다, 억제하다", "Budget limits constrained our options.", "limit, restrict, confine"),
    ("contribute", "기여하다, 공헌하다", "She contributed ideas to the project.", "give, add, donate"),
    ("convene", "소집하다, 소집되다", "A committee was convened.", "assemble, gather, meet"),
    ("coordinate", "조율하다, 조정하다", "Coordinate efforts across teams.", "organize, harmonize, align"),
    ("core", "핵심, 중심", "The core of the argument is simple.", "center, heart, essence"),
    ("corporate", "기업의, 법인의", "Corporate culture matters.", "business, company, organizational"),
    ("correspond", "일치하다; 서신을 주고받다", "The results correspond to expectations.", "match, agree, align"),
    ("criteria", "기준 (criterion의 복수)", "What criteria do you use?", "standards, measures, requirements"),
    ("deduce", "추론하다, 추리하다", "We can deduce the answer from clues.", "conclude, infer, reason"),
    ("demonstrate", "입증하다, 시연하다", "Demonstrate how it works.", "show, prove, display"),
    ("document", "기록하다; 문서", "Document all your findings.", "record, write down, report"),
    ("dominate", "지배하다", "One company dominates the market.", "control, rule, govern"),
    ("emphasis", "강조, 중점", "Place emphasis on safety.", "stress, importance, weight"),
    ("ensure", "확실히 하다, 보장하다", "Ensure all doors are locked.", "make sure, guarantee, secure"),
    ("exclude", "제외하다, 배제하다", "Exclude irrelevant information.", "leave out, omit, ban"),
    ("framework", "틀, 체계, 구조", "Work within the legal framework.", "structure, system, outline"),
    ("fund", "자금을 지원하다; 자금", "The grant funds research.", "finance, sponsor, support"),
    ("illustrate", "설명하다; 삽화를 넣다", "Illustrate your point with examples.", "show, explain, demonstrate"),
    ("immigrate", "이민 오다", "Many people immigrate for work.", "move in, settle, relocate"),
    ("imply", "암시하다, 내포하다", "His silence implies agreement.", "suggest, hint, indicate"),
    ("initial", "초기의, 처음의", "My initial reaction was surprise.", "first, early, beginning"),
    ("instance", "사례, 경우", "In this instance, rules apply.", "example, case, occurrence"),
    ("interact", "상호 작용하다", "Students interact with peers daily.", "communicate, engage, connect"),
    ("justify", "정당화하다", "How do you justify this expense?", "explain, defend, rationalize"),
    ("layer", "층, 겹", "Add another layer of paint.", "level, stratum, coating"),
    ("link", "연결하다; 연결", "These events are closely linked.", "connect, join, relate"),
    ("locate", "위치를 찾다; ~에 위치하다", "We need to locate the file.", "find, position, place"),
    ("maximum", "최대(값); 최대의", "Reach your maximum potential.", "greatest, highest, peak"),
    ("mechanism", "메커니즘, 작동 원리", "What mechanism drives this?", "system, process, device"),
    ("media", "언론, 미디어", "The media reported the story.", "press, broadcast, news"),
    ("minimum", "최소(값); 최소의", "Keep the cost to a minimum.", "least, lowest, smallest"),
    ("monitor", "감시하다, 추적하다", "Monitor your progress carefully.", "observe, watch, track"),
    ("motive", "동기, 이유", "What was his motive?", "reason, purpose, aim"),
    ("neutral", "중립적인", "Stay neutral in the dispute.", "impartial, unbiased, objective"),
    ("nevertheless", "그럼에도 불구하고", "He failed; nevertheless, he tried.", "however, yet, still"),
    ("obvious", "명백한, 분명한", "The answer is obvious.", "clear, evident, apparent"),
    ("occupy", "차지하다; 거주하다", "They occupy the top floor.", "inhabit, fill, use"),
    ("option", "선택(지)", "You have several options.", "choice, alternative, possibility"),
    ("output", "산출량, 결과물", "Increase the factory's output.", "production, yield, result"),
    ("overall", "전반적인, 종합적인", "The overall result is positive.", "total, general, comprehensive"),
    ("parallel", "평행한; 유사한", "There are parallel developments.", "simultaneous, corresponding, similar"),
    ("parameter", "매개변수; 한계", "Work within the set parameters.", "limit, boundary, variable"),
    ("phase", "단계, 국면", "We are in the planning phase.", "stage, period, step"),
    ("predict", "예측하다", "Can you predict the outcome?", "forecast, foresee, anticipate"),
    ("prior", "이전의, 우선의", "Prior knowledge helps learning.", "earlier, former, previous"),
    ("professional", "전문적인; 전문가", "She gave professional advice.", "skilled, expert, qualified"),
    ("project", "프로젝트; 예측하다", "We finished the project on time.", "task, assignment, undertaking"),
    ("promote", "촉진하다; 홍보하다", "Promote healthy habits.", "support, advance, encourage"),
    ("proportion", "비율, 비중", "A large proportion of students passed.", "fraction, ratio, share"),
    ("publish", "출판하다, 발표하다", "She published her findings.", "release, issue, print"),
    ("react", "반응하다", "How did you react to the news?", "respond, act, reply"),
    ("register", "등록하다; 등록부", "Register your name on the list.", "record, enroll, note"),
    ("rely", "의존하다, 믿다", "You can rely on this system.", "depend on, count on, trust"),
    ("remove", "제거하다", "Remove the excess data.", "eliminate, take away, delete"),
    ("scheme", "계획, 제도", "A new payment scheme was introduced.", "plan, system, program"),
    ("sequence", "순서, 연속", "Follow the correct sequence.", "order, series, succession"),
    ("shift", "변화; 이동하다", "There has been a shift in policy.", "change, move, transfer"),
    ("specify", "명시하다, 구체적으로 말하다", "Please specify the requirements.", "state, define, detail"),
    ("sufficient", "충분한", "Is there sufficient evidence?", "enough, adequate, ample"),
    ("task", "과제, 업무", "Complete the task on time.", "job, assignment, duty"),
    ("technical", "기술적인, 전문적인", "This requires technical knowledge.", "specialized, skilled, expert"),
    ("technique", "기술, 기법", "Practice this painting technique.", "method, skill, procedure"),
    ("technology", "기술, 과학 기술", "Modern technology is advancing.", "innovation, science, tools"),
    ("valid", "유효한, 타당한", "Make a valid point.", "sound, legitimate, acceptable"),
    ("volume", "부피; 양, 음량", "A large volume of data.", "amount, quantity, mass"),

    # Sublist 4
    ("access", "접근; 접근하다", "Access to education is a right.", "entry, means, approach"),
    ("adequate", "충분한, 적절한", "The resources are adequate.", "sufficient, satisfactory, enough"),
    ("annual", "연간의, 매년의", "The company holds annual reviews.", "yearly, once-a-year"),
    ("apparent", "명백한, 분명한", "Her talent was apparent.", "obvious, evident, clear"),
    ("approximate", "대략적인; 근사치", "Give an approximate figure.", "rough, estimated, close"),
    ("attitude", "태도, 자세", "Have a positive attitude.", "outlook, view, opinion"),
    ("attribute", "특성; ~의 탓으로 돌리다", "Intelligence is not her only attribute.", "quality, trait, characteristic"),
    ("civil", "시민의, 민간의", "Civil rights are fundamental.", "civic, public, citizen"),
    ("code", "규범, 코드; 암호", "Follow the code of conduct.", "system, rules, protocol"),
    ("commit", "전념하다; 저지르다", "They committed to the plan.", "pledge, dedicate, carry out"),
    ("communicate", "의사소통하다, 전달하다", "Communicate your ideas clearly.", "convey, share, express"),
    ("concentrate", "집중하다", "Concentrate on the main points.", "focus, center, direct"),
    ("confer", "수여하다; 협의하다", "They conferred about the plan.", "grant, discuss, consult"),
    ("contrast", "대조하다; 대조", "Contrast the two approaches.", "compare, differ, oppose"),
    ("cycle", "순환, 주기", "The water cycle is important.", "series, rotation, pattern"),
    ("debate", "토론하다; 토론", "The debate was lively.", "discussion, argument, dispute"),
    ("despite", "~에도 불구하고", "She won despite the difficulty.", "in spite of, regardless of"),
    ("dimension", "차원; 측면", "Consider every dimension of the problem.", "aspect, extent, measure"),
    ("domestic", "국내의; 가정의", "Domestic policy matters.", "home, national, internal"),
    ("emerge", "나타나다, 출현하다", "New evidence emerged.", "appear, arise, surface"),
    ("error", "오류, 실수", "Correct the error immediately.", "mistake, fault, inaccuracy"),
    ("ethnic", "민족의, 인종의", "Ethnic diversity enriches society.", "cultural, racial, national"),
    ("goal", "목표, 목적", "Set a clear goal.", "aim, objective, target"),
    ("grant", "수여하다; 보조금", "They granted him permission.", "give, award, bestow"),
    ("hence", "따라서, 그러므로", "The data was incomplete; hence, the error.", "therefore, thus, consequently"),
    ("hypothesis", "가설", "Test your hypothesis with data.", "theory, assumption, proposition"),
    ("implement", "실행하다, 시행하다", "Implement the new system.", "carry out, execute, apply"),
    ("implication", "함축, 시사점; 결과", "Consider the implications carefully.", "consequence, significance, meaning"),
    ("impose", "부과하다, 강요하다", "Don't impose your views on others.", "enforce, force, inflict"),
    ("integrate", "통합하다", "Integrate all the data sources.", "combine, merge, unify"),
    ("internal", "내부의, 국내의", "An internal review was conducted.", "inner, inside, interior"),
    ("levy", "세금을 부과하다; 세금", "A levy was placed on imports.", "tax, charge, fee"),
    ("logical", "논리적인", "That is a logical conclusion.", "reasonable, rational, sensible"),
    ("margin", "여백; 차이, 마진", "Write notes in the margin.", "edge, border, boundary"),
    ("medical", "의학의, 의료의", "Get medical advice from a doctor.", "health, clinical, healthcare"),
    ("mental", "정신적인, 마음의", "Mental health is important.", "psychological, cognitive, intellectual"),
    ("modify", "수정하다, 변경하다", "Modify your approach slightly.", "change, adjust, alter"),
    ("network", "네트워크, 연결망", "She has a strong professional network.", "system, web, connections"),
    ("notion", "개념, 생각", "I have no notion of what happened.", "idea, belief, concept"),
    ("objective", "목표; 객관적인", "Our objective is to succeed.", "goal, aim, target"),
    ("orient", "방향을 잡다; 적응시키다", "Orient yourself to the new environment.", "align, direct, position"),
    ("outcome", "결과", "The outcome was unexpected.", "result, consequence, effect"),
    ("participant", "참가자", "All participants signed a form.", "member, contributor, attendee"),
    ("persist", "지속하다, 계속하다", "Persist despite setbacks.", "continue, endure, persevere"),
    ("phenomenon", "현상", "Language change is a natural phenomenon.", "event, occurrence, fact"),
    ("philosophy", "철학", "Philosophy challenges our assumptions.", "worldview, thinking, doctrine"),
    ("physical", "물리적인; 신체의", "Physical exercise is essential.", "bodily, material, tangible"),
    ("radical", "근본적인; 급진적인", "A radical change was needed.", "extreme, fundamental, drastic"),
    ("random", "무작위의", "Select samples at random.", "arbitrary, haphazard, chance"),
    ("reinforce", "강화하다, 보강하다", "Reinforce the key points.", "strengthen, support, bolster"),
    ("resolve", "해결하다; 결심하다", "They resolved their differences.", "settle, solve, fix"),
    ("retain", "유지하다, 보유하다", "Retain the original copy.", "keep, maintain, preserve"),
    ("series", "일련, 시리즈", "A series of experiments.", "sequence, string, chain"),
    ("simulate", "모의 실험하다, 시뮬레이션하다", "Simulate real-world scenarios.", "imitate, model, replicate"),
    ("sole", "유일한, 단독의", "She is the sole owner.", "only, single, exclusive"),
    ("somewhat", "다소, 어느 정도", "The result was somewhat surprising.", "rather, fairly, slightly"),
    ("statistic", "통계(치)", "This statistic is alarming.", "figure, number, data point"),
    ("subsequent", "이후의, 차후의", "Subsequent events proved him right.", "later, following, ensuing"),
    ("substitute", "대체하다; 대체물", "Use water as a substitute for milk.", "replacement, alternative, stand-in"),
    ("sustain", "유지하다, 지탱하다", "Can we sustain this growth?", "maintain, support, continue"),
    ("symbol", "상징, 기호", "The dove is a symbol of peace.", "sign, representation, emblem"),
    ("target", "목표; 대상", "What is your target audience?", "goal, aim, objective"),
    ("thus", "따라서, 그러므로", "He studied hard; thus, he passed.", "therefore, hence, consequently"),
    ("trend", "경향, 추세", "The trend is toward remote work.", "tendency, direction, movement"),
    ("uniform", "균일한, 통일된; 제복", "Apply uniform standards.", "consistent, identical, even"),
    ("utilize", "활용하다, 이용하다", "Utilize all available resources.", "use, employ, apply"),

    # Sublist 5
    ("accurate", "정확한", "Provide accurate information.", "correct, precise, exact"),
    ("acknowledge", "인정하다, 인식하다", "Acknowledge your mistakes.", "admit, recognize, accept"),
    ("aggregate", "집계; 합계의", "The aggregate score was high.", "total, combined, collective"),
    ("allocate", "할당하다, 배분하다", "Allocate funds to each department.", "distribute, assign, apportion"),
    ("assign", "배정하다, 할당하다", "She was assigned the project.", "give, appoint, designate"),
    ("attach", "첨부하다, 붙이다", "Attach the file to the email.", "fasten, connect, join"),
    ("author", "저자, 작가", "The author wrote a bestseller.", "writer, creator, originator"),
    ("bond", "유대, 결합; 채권", "Their shared values created a bond.", "tie, link, connection"),
    ("brief", "간략한; 브리핑하다", "Give a brief summary.", "short, concise, quick"),
    ("capable", "능력 있는, 유능한", "She is capable of great things.", "able, competent, skilled"),
    ("cite", "인용하다", "Cite your sources clearly.", "quote, reference, mention"),
    ("cooperate", "협력하다, 협동하다", "Teams must cooperate to succeed.", "collaborate, work together, partner"),
    ("deny", "부인하다, 거부하다", "She denied involvement.", "reject, dispute, refuse"),
    ("differentiate", "구별하다, 차별화하다", "Differentiate between the options.", "distinguish, separate, discriminate"),
    ("dispose", "처분하다, 처리하다", "Dispose of waste responsibly.", "discard, throw away, eliminate"),
    ("draft", "초안; 초안을 작성하다", "Submit your first draft by Friday.", "rough version, outline, sketch"),
    ("enable", "가능하게 하다", "Technology enables fast communication.", "allow, permit, facilitate"),
    ("energy", "에너지, 힘", "Solar energy is renewable.", "power, force, fuel"),
    ("enforce", "집행하다, 강제하다", "The police enforce the law.", "compel, implement, apply"),
    ("entity", "존재, 개체; 법인", "A company is a legal entity.", "unit, thing, object, body"),
    ("equivalent", "동등한; 동등물", "Find an equivalent expression.", "equal, comparable, corresponding"),
    ("evolve", "진화하다, 발전하다", "Species evolve over time.", "develop, change, adapt"),
    ("expand", "확장하다, 팽창하다", "The company plans to expand.", "grow, increase, extend"),
    ("expose", "노출시키다; 폭로하다", "The study exposed the flaws.", "reveal, uncover, disclose"),
    ("external", "외부의", "External factors affected the result.", "outside, outer, exterior"),
    ("facilitate", "촉진하다, 용이하게 하다", "This tool facilitates learning.", "enable, ease, assist"),
    ("fundamental", "근본적인, 기본적인", "Trust is fundamental to success.", "basic, essential, core"),
    ("generate", "생성하다, 만들어 내다", "Solar panels generate electricity.", "produce, create, yield"),
    ("generation", "세대", "The next generation will benefit.", "age group, era, cohort"),
    ("image", "이미지, 이미지; 상(像)", "The image was blurry.", "picture, representation, photo"),
    ("liberal", "자유로운; 진보적인", "A liberal approach is open-minded.", "open-minded, tolerant, broad"),
    ("license", "면허, 허가", "You need a license to drive.", "permission, permit, authorization"),
    ("logic", "논리", "The logic of the argument holds.", "reasoning, rationale, sense"),
    ("marginal", "미미한, 한계의", "Only marginal improvements were seen.", "slight, minor, small"),
    ("migrate", "이주하다, 이동하다", "Birds migrate south in winter.", "move, travel, relocate"),
    ("military", "군사의; 군대", "Military strategy changed.", "armed, defense, combat"),
    ("minimal", "최소한의, 아주 적은", "The impact was minimal.", "small, minor, negligible"),
    ("minority", "소수(집단)", "A minority opposed the change.", "small group, few"),
    ("mode", "방식, 모드", "Change the mode of transport.", "method, way, form"),
    ("mutual", "상호의, 공통의", "Mutual respect is essential.", "shared, reciprocal, joint"),
    ("overseas", "해외에서; 해외의", "She studied overseas.", "abroad, internationally"),
    ("panel", "패널, 전문가 집단", "The panel reviewed the proposal.", "group, committee, board"),
    ("paradigm", "패러다임, 모범 사례", "This is a new paradigm.", "model, framework, example"),
    ("passive", "수동적인", "Don't be passive; take action.", "inactive, submissive, inert"),
    ("perspective", "관점, 시각", "Consider a new perspective.", "viewpoint, standpoint, angle"),
    ("precise", "정밀한, 정확한", "Be precise in your measurements.", "exact, accurate, specific"),
    ("prime", "주요한; 최상의", "Prime minister leads the country.", "main, chief, leading"),
    ("prohibit", "금지하다", "Smoking is prohibited here.", "ban, forbid, disallow"),
    ("ratio", "비율, 비", "The ratio of boys to girls.", "proportion, fraction, comparison"),
    ("recover", "회복하다", "She recovered quickly.", "heal, return to normal, regain"),
    ("reveal", "드러내다, 밝히다", "The report revealed the truth.", "show, disclose, uncover"),
    ("scope", "범위, 영역", "The scope of the project is wide.", "extent, range, reach"),
    ("sector", "부문, 분야", "The public sector employs many.", "area, part, division"),
    ("stable", "안정적인", "The economy is stable.", "steady, firm, secure"),
    ("status", "지위, 상태", "What is your employment status?", "position, rank, standing"),
    ("straightforward", "간단한, 직접적인", "The task is straightforward.", "simple, clear, easy"),
    ("subsidy", "보조금", "Farming subsidies help rural areas.", "grant, allowance, support"),
    ("symbolic", "상징적인", "A symbolic gesture of peace.", "representative, emblematic"),
    ("thesis", "논문; 논지", "State your thesis clearly.", "argument, claim, proposition"),
    ("trace", "추적하다; 흔적", "Trace the history of the word.", "follow, track, find"),
    ("transport", "운송하다; 교통수단", "Transport goods safely.", "carry, convey, move"),
    ("ultimate", "궁극적인, 최종적인", "The ultimate goal is peace.", "final, supreme, highest"),
    ("unique", "독특한, 유일한", "Each person is unique.", "one-of-a-kind, distinctive, singular"),
    ("vehicle", "차량; 수단", "Use any available vehicle.", "transport, conveyance, carrier"),
    ("visible", "눈에 보이는, 가시적인", "The change was clearly visible.", "observable, apparent, perceptible"),

    # Sublist 6
    ("abstract", "추상적인; 요약", "Mathematics deals with abstract concepts.", "theoretical, conceptual, notional"),
    ("aid", "도움, 원조; 돕다", "Foreign aid was sent to the region.", "help, assistance, support"),
    ("channel", "경로, 채널", "Use official channels.", "route, path, medium"),
    ("classic", "전형적인; 고전", "A classic experiment in physics.", "definitive, exemplary, model"),
    ("comprehensive", "포괄적인, 종합적인", "A comprehensive review was done.", "thorough, complete, full"),
    ("comprise", "구성하다, 이루다", "The team comprises five people.", "consist of, include, contain"),
    ("confirm", "확인하다, 확정하다", "Confirm your booking.", "verify, validate, establish"),
    ("contrary", "반대의; 반대", "On the contrary, she agreed.", "opposite, opposing, reverse"),
    ("convert", "전환하다, 변환하다", "Convert the file to PDF.", "change, transform, switch"),
    ("couple", "한 쌍; 두어 개", "A couple of minor errors.", "pair, two, a few"),
    ("decade", "10년", "Over the past decade.", "ten years, ten-year period"),
    ("decline", "감소하다; 거절하다", "Interest in the topic declined.", "decrease, fall, reduce"),
    ("discretion", "재량, 분별력", "Use your discretion wisely.", "judgment, choice, freedom"),
    ("domain", "영역, 분야", "Her domain is molecular biology.", "field, area, sphere"),
    ("equate", "동일시하다", "Don't equate success with money.", "equalize, compare, identify"),
    ("ethical", "윤리적인", "Consider the ethical implications.", "moral, principled, right"),
    ("exhibit", "전시하다; 나타내다", "They exhibited their work.", "display, show, present"),
    ("expertise", "전문 지식, 전문성", "She has expertise in data analysis.", "skill, knowledge, proficiency"),
    ("explicit", "명시적인, 명백한", "Give explicit instructions.", "clear, direct, specific"),
    ("exploit", "활용하다; 착취하다", "Exploit all available resources.", "use, utilize, take advantage of"),
    ("federal", "연방의", "Federal law applies everywhere.", "national, central, governmental"),
    ("flexible", "유연한, 융통성 있는", "A flexible schedule helps.", "adaptable, open, adjustable"),
    ("furthermore", "더욱이, 게다가", "Furthermore, the data supports this.", "moreover, additionally, also"),
    ("global", "세계적인, 전 지구적인", "A global perspective is important.", "worldwide, international, universal"),
    ("grade", "등급; 성적", "The product is of high grade.", "level, quality, rank"),
    ("guarantee", "보장하다; 보증", "I guarantee the accuracy.", "assure, promise, ensure"),
    ("hierarchy", "위계, 계층 구조", "Understand the hierarchy of needs.", "ranking, order, structure"),
    ("highlight", "강조하다; 하이라이트", "Highlight the key findings.", "emphasize, stress, underline"),
    ("implicit", "암묵적인, 내포된", "There was an implicit threat.", "implied, indirect, understood"),
    ("incorporate", "통합하다, 포함하다", "Incorporate feedback into the draft.", "include, integrate, embed"),
    ("innovate", "혁신하다", "Innovate to stay competitive.", "invent, create, pioneer"),
    ("intelligent", "지적인, 영리한", "An intelligent approach is needed.", "smart, clever, knowledgeable"),
    ("intense", "강렬한, 극심한", "Intense competition drives innovation.", "extreme, powerful, strong"),
    ("investigate", "조사하다, 수사하다", "Investigate the cause of failure.", "examine, probe, research"),
    ("lecture", "강의; 강의하다", "Attend the lecture on Friday.", "talk, lesson, address"),
    ("mature", "성숙한; 성숙하다", "A mature market grows slowly.", "developed, grown, adult"),
    ("maximize", "극대화하다", "Maximize your chances of success.", "increase, optimize, boost"),
    ("minimize", "최소화하다", "Minimize the risk of error.", "reduce, decrease, limit"),
    ("motivation", "동기(부여)", "High motivation leads to success.", "drive, incentive, desire"),
    ("novel", "새로운, 신기한; 소설", "A novel approach was taken.", "new, innovative, original"),
    ("plot", "줄거리; 도표; 계획하다", "Plot the data on a graph.", "plan, map, chart"),
    ("plus", "게다가; 장점", "This is a plus, not a minus.", "advantage, benefit, bonus"),
    ("practitioner", "실무자, 전문가", "She is a medical practitioner.", "professional, expert, specialist"),
    ("preliminary", "예비의, 사전의", "A preliminary study was done.", "initial, introductory, early"),
    ("principal", "주요한; 교장", "The principal reason is cost.", "main, primary, chief"),
    ("propose", "제안하다", "She proposed a solution.", "suggest, recommend, put forward"),
    ("recover", "회복하다, 되찾다", "The economy will recover.", "regain, restore, rebound"),
    ("refine", "개선하다, 정제하다", "Refine your argument.", "improve, polish, perfect"),
    ("regime", "체제, 정권", "The regime changed abruptly.", "government, system, rule"),
    ("reluctant", "내키지 않는, 꺼리는", "He was reluctant to agree.", "unwilling, hesitant, resistant"),
    ("rigid", "엄격한, 굳은", "A rigid schedule limits flexibility.", "stiff, inflexible, fixed"),
    ("stability", "안정성", "Economic stability is vital.", "steadiness, firmness, balance"),
    ("style", "스타일, 방식", "Develop your own style.", "manner, way, approach"),
    ("survive", "살아남다, 존속하다", "Species must adapt to survive.", "endure, live on, persist"),
    ("suspend", "중단하다; 정직시키다", "Suspend all activities.", "halt, pause, stop"),

    # Sublist 7
    ("adapt", "적응하다, 조정하다", "Adapt to changing circumstances.", "adjust, modify, change"),
    ("ambiguous", "모호한", "The instruction was ambiguous.", "unclear, vague, uncertain"),
    ("analogy", "유추, 비유", "Use an analogy to explain.", "comparison, parallel, metaphor"),
    ("anticipate", "예상하다, 기대하다", "Anticipate problems before they arise.", "expect, foresee, predict"),
    ("assemble", "모으다; 조립하다", "Assemble the evidence.", "gather, collect, bring together"),
    ("bias", "편향, 편견", "Avoid bias in research.", "prejudice, tendency, slant"),
    ("cease", "중단하다, 멈추다", "Production will cease next month.", "stop, end, halt"),
    ("challenge", "도전; 어려운 일", "This is a major challenge.", "difficulty, problem, test"),
    ("clarify", "명확히 하다", "Please clarify your point.", "explain, clear up, elaborate"),
    ("clause", "조항; 절(節)", "Review the final clause.", "section, provision, term"),
    ("coherent", "일관된, 논리적인", "Present a coherent argument.", "logical, clear, consistent"),
    ("coincide", "동시에 일어나다; 일치하다", "The dates coincide.", "match, correspond, align"),
    ("commence", "시작하다", "Work will commence in January.", "begin, start, initiate"),
    ("compatible", "양립할 수 있는, 호환되는", "Are the systems compatible?", "suitable, consistent, matching"),
    ("compile", "편집하다, 모으다", "Compile a list of sources.", "collect, gather, assemble"),
    ("complement", "보완하다; 보완물", "The colors complement each other.", "enhance, complete, supplement"),
    ("conceive", "생각해내다, 임신하다", "He conceived a new idea.", "think up, invent, imagine"),
    ("conform", "따르다, 순응하다", "Conform to the standards.", "comply, follow, obey"),
    ("converse", "대화하다; 반대의", "We conversed for an hour.", "talk, chat, discuss"),
    ("detect", "감지하다, 발견하다", "Detect errors in the code.", "find, identify, discover"),
    ("discrete", "개별적인, 분리된", "Discrete steps in a process.", "separate, distinct, individual"),
    ("eliminate", "제거하다, 없애다", "Eliminate errors from the text.", "remove, get rid of, eradicate"),
    ("empirical", "경험적인, 실증적인", "Use empirical data.", "observed, experimental, measured"),
    ("format", "형식, 포맷; 서식을 맞추다", "Use the correct format.", "layout, structure, design"),
    ("forthcoming", "곧 있을, 다가오는", "The forthcoming report.", "upcoming, approaching, imminent"),
    ("found", "설립하다", "They founded the company.", "establish, create, set up"),
    ("identical", "동일한, 똑같은", "The two results were identical.", "same, equal, matching"),
    ("ideology", "이념, 사상 체계", "The ideology shaped policy.", "beliefs, doctrine, worldview"),
    ("inadequate", "불충분한, 부적절한", "Inadequate preparation leads to failure.", "insufficient, poor, lacking"),
    ("incline", "경향이 있다; 기울다", "She inclines toward caution.", "tend, lean, be disposed"),
    ("inhibit", "억제하다, 방해하다", "Fear can inhibit learning.", "hinder, prevent, restrain"),
    ("initiate", "시작하다, 개시하다", "Initiate the review process.", "start, begin, launch"),
    ("inherent", "본래의, 내재된", "Inherent flaws in the system.", "inborn, natural, built-in"),
    ("insight", "통찰(력)", "Gain insight into the problem.", "understanding, perception, awareness"),
    ("integral", "필수적인, 핵심적인", "An integral part of the plan.", "essential, fundamental, central"),
    ("invoke", "원용하다; 불러일으키다", "Invoke the rule of law.", "call on, appeal to, apply"),
    ("label", "분류하다; 라벨", "Label each sample carefully.", "name, tag, classify"),
    ("negate", "무효화하다, 부정하다", "Errors negate the results.", "cancel, nullify, invalidate"),
    ("norm", "규범, 표준", "Social norms vary.", "standard, rule, convention"),
    ("overlap", "겹치다; 중복", "The two topics overlap.", "intersect, coincide, share"),
    ("partner", "파트너, 동반자", "Find a business partner.", "associate, colleague, collaborator"),
    ("rational", "이성적인, 합리적인", "Make a rational decision.", "logical, reasoned, sensible"),
    ("refine", "개선하다, 정제하다", "Refine your argument.", "improve, polish, perfect"),
    ("reluctant", "꺼리는, 마지못한", "He was reluctant to agree.", "unwilling, hesitant, resistant"),
    ("rigid", "굳은, 엄격한", "A rigid schedule limits flexibility.", "stiff, inflexible, fixed"),
    ("simulate", "모의 실험하다", "Simulate the experiment digitally.", "model, imitate, replicate"),
    ("thesis", "논문; 논지", "Develop a clear thesis.", "argument, point, claim"),
    ("trace", "추적하다; 흔적", "Trace the source of the problem.", "track, follow, find"),

    # Sublist 8
    ("abbreviate", "줄이다, 약자로 쓰다", "Abbreviate the long title.", "shorten, condense, truncate"),
    ("accommodate", "수용하다; 적응하다", "Can the venue accommodate 200 people?", "hold, adapt, house"),
    ("accumulate", "축적하다, 모으다", "Accumulate evidence over time.", "gather, build up, collect"),
    ("ambiguity", "모호함, 애매함", "Avoid ambiguity in your writing.", "vagueness, uncertainty, unclearness"),
    ("arbitrary", "임의적인, 자의적인", "The decision seemed arbitrary.", "random, chance, unreasoned"),
    ("chart", "도표, 차트; 도표로 나타내다", "Chart the progress over time.", "diagram, graph, map"),
    ("chronological", "시간순의", "Present events in chronological order.", "sequential, in order, time-based"),
    ("colleague", "동료", "Discuss with your colleagues.", "co-worker, peer, associate"),
    ("constraint", "제약, 제한", "Work within budget constraints.", "limit, restriction, boundary"),
    ("controversy", "논란, 논쟁", "The decision caused controversy.", "debate, dispute, argument"),
    ("correlation", "상관관계", "There is a correlation between X and Y.", "relationship, connection, link"),
    ("criterion", "기준 (criteria의 단수)", "The main criterion is accuracy.", "standard, measure, rule"),
    ("dynamic", "역동적인; 역학", "A dynamic environment.", "changing, active, energetic"),
    ("efficient", "효율적인", "An efficient method saves time.", "productive, effective, streamlined"),
    ("enhance", "향상시키다, 강화하다", "Enhance the quality of work.", "improve, strengthen, boost"),
    ("finite", "유한한, 한정된", "Resources are finite.", "limited, bounded, restricted"),
    ("fluctuate", "변동하다, 오르내리다", "Prices fluctuate with demand.", "vary, change, swing"),
    ("forthcoming", "다가오는, 곧 나올", "Look for forthcoming events.", "upcoming, approaching, imminent"),
    ("innovation", "혁신", "Technological innovation drives growth.", "invention, novelty, breakthrough"),
    ("intelligent", "지적인, 총명한", "An intelligent observation.", "smart, clever, perceptive"),
    ("invoke", "원용하다", "Invoke academic freedom.", "cite, appeal to, apply"),
    ("migrate", "이주하다", "People migrate for work.", "move, relocate, travel"),
    ("paradigm", "패러다임, 전형", "A paradigm shift occurred.", "model, framework, standard"),

    # Sublist 9
    ("collapse", "무너지다, 붕괴하다", "The system may collapse.", "fail, break down, fall"),
    ("concurrent", "동시의, 병행하는", "Concurrent tasks were handled.", "simultaneous, parallel, overlapping"),
    ("contemporary", "현대의; 동시대의", "Contemporary art reflects society.", "modern, current, present-day"),
    ("contradict", "반박하다, 모순되다", "Don't contradict the evidence.", "oppose, deny, dispute"),
    ("controversial", "논쟁이 많은", "A controversial decision.", "disputed, debated, contested"),
    ("correlate", "상관관계가 있다", "These variables correlate.", "relate, correspond, connect"),
    ("deviate", "벗어나다, 이탈하다", "Don't deviate from the plan.", "stray, diverge, depart"),
    ("dominant", "지배적인, 우세한", "The dominant theory.", "leading, primary, main"),
    ("exceed", "초과하다, 능가하다", "Results exceeded expectations.", "surpass, go beyond, outdo"),
    ("fluctuate", "변동하다", "Prices fluctuate daily.", "vary, change, oscillate"),

    # Sublist 10
    ("adjacent", "인접한, 옆의", "The rooms are adjacent.", "next to, neighboring, nearby"),
    ("albeit", "비록 ~이지만", "He succeeded, albeit slowly.", "although, even though, though"),
    ("attain", "달성하다, 이루다", "Attain a high level of skill.", "achieve, reach, accomplish"),
    ("cease", "끝내다, 중단하다", "All activity must cease.", "stop, end, discontinue"),
    ("commence", "시작하다", "The course commences in September.", "begin, start, open"),
    ("constitute", "구성하다, ~에 해당하다", "This constitutes a violation.", "make up, represent, form"),
    ("contradict", "반박하다", "The findings contradict the theory.", "oppose, deny, refute"),
    ("deviate", "이탈하다", "Don't deviate from the protocol.", "diverge, differ, depart"),
    ("forthcoming", "다가오는", "The forthcoming conference.", "upcoming, imminent, approaching"),
]
